blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

	# Blogpage
	path('', views.blog_view, name='blog'),

	# Post Details
	path('post/<pid>/', views.blog_detail_view, name='blog-detail'),

	# Blog Category
	path('category/<cid>/', views.blog_category_view, name="blog-category"),

	# Blog Tags
	path('tag/<slug:tag_slug>/', views.blog_tags, name='blog-tag'),

	# Add Post Comment
	path('ajax-add-comment/<int:pid>/', views.ajax_add_comment, name='ajax-add-comment'),

]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [

	# Homepage
	path('', views.index, name='index'),
	
	# Product
	path('products/', views.products_list_view, name='products-list'),
	path('product/<pid>/', views.product_detail_view, name='products-detail'),

	# Category
	path('category/', views.category_list_view, name='category-list'),
	path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

	# Vendor
	path('vendors/', views.vendor_list_view, name='vendor-list'),
	path('vendor/<vid>/', views.vendor_detail_view, name='vendor-detail'),

	# Tags
	path('products/tag/<slug:tag_slug>/', views.tags_list, name='tags'),

	# Add Product Review
	path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax-add-review'),

	# Seacrh 
	path('search/', views.search_view, name='search'),

	# Product Filter
	path('filter-product/', views.filter_product, name='filter-product'),

	# Add To Cart 
	path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

	# Cart Page
	path('cart/', views.cart_view, name='cart'),

	# Delete from cart
	path('delete-from-cart/', views.delete_from_cart, name='delete-from-cart'),

	# Update cart
	path('update-cart/', views.update_cart, name='update-cart'),

	# Wishlist page
	path('wishlist/', views.wishlist_view, name='wishlist'),

	# Add To Wishlist
	path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),

	# Remove From Wishlist
	path('remove-from-wishlist/', views.remove_from_wishlist, name='remove-from-wishlist'),

	# Contact
	path('contact/', views.contact, name='contact'),

	# Ajax Contact From
	path('ajax-contact-form/', views.ajax_contact_form, name='ajax-contact-form'),

	# About Us
	path('about/', views.about, name='about'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


### TEST ###

# handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewFrom(forms.ModelForm):
	review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write review', \
		'style': 'width: 100%; border: none; background: #f5f5f5; \
		padding: 5px 10px; height: 100px; border-radius: 5px 5px 0px 0px; \
		border-bottom: 2px solid #7fad39; transition: all 0.5s; margin-top: 15px; \
		margin-bottom: 15px;'}))

	class Meta:
		model = ProductReview
		fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Avg, F, ExpressionWrapper, DecimalField
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.core import serializers
from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, \
ProductImages, ProductReview, Wishlist, Address, ContactUs
from core.forms import ProductReviewFrom
from taggit.models import Tag

def index(request):
	products = Product.objects.filter(product_status='published', featured=True)

	special_offers = Product.objects.filter(product_status='published').annotate(
		discount_percentage=ExpressionWrapper(
			((F('old_price') - F('price')) / F('old_price')) * 100,
			output_field=DecimalField()
		)
    ).order_by('-discount_percentage')[:9]
    
	oldest_products = Product.objects.filter(product_status='published').order_by('date')

	context = {
		"products": products,
		"special_offers": special_offers,
		"oldest_products": oldest_products,
	}
	return render(request, 'core/index.html', context)

def products_list_view(request):
	products = Product.objects.filter(product_status='published')
	context = {
		"products": products
	}
	return render(request, 'core/product-list.html', context)

def category_list_view(request):
	categories = Category.objects.all()
	context = {
		"categories": categories,
	}
	return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
	category = Category.objects.get(cid=cid)
	products = Product.objects.filter(product_status='published', category=category)
	context = {
		"category": category,
		"products": products,
	}
	return render(request, 'core/category-products-list.html', context)

def vendor_list_view(request):
	vendors = Vendor.objects.all()
	context = {
		'vendors': vendors,
	}
	return render(request, 'core/vendor-list.html', context)

def vendor_detail_view(request, vid):
	vendor = Vendor.objects.get(vid=vid)
	products = Product.objects.filter(product_status='published', vendor=vendor)
	context = {
		'vendor': vendor,
		'products': products,
	}
	return render(request, 'core/vendor-detail.html', context)

def product_detail_view(request, pid):
	product = Product.objects.get(pid=pid)
	# product = get_object_or_404(Product, pid=pid)
	products = Product.objects.filter(category=product.category).exclude(pid=pid)
	p_image = product.p_images.all()

	reviews = ProductReview.objects.filter(product=product).order_by('-date')
	average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
	review_form = ProductReviewFrom()

	make_review = True
	if request.user.is_authenticated:
		user_review_count = ProductReview.objects.filter(user=request.user, product=product).count() 

		if user_review_count > 0:
			make_review = False

	context = {
		'product': product,
		'p_image': p_image,
		'products': products,
		'reviews': reviews,
		'average_rating': average_rating,
		'review_form': review_form,
		'make_review': make_review,
	}
	return render(request, 'core/product-detail.html', context)

def tags_list(request, tag_slug=None):
	products = Product.objects.filter(product_status='published').order_by('-id')

	tag = None
	if tag_slug:
		tag = Tag.objects.get(slug=tag_slug)
		# tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])

	context = {
		'products': products,
		'tag': tag,
	}

	return render(request, 'core/tag.html', context)

def ajax_add_review(request, pid):
	product = Product.objects.get(pk=pid)
	user = request.user
	image = user.image.url

	review = ProductReview.objects.create(
		user=user,
		product=product,
		review=request.POST['review'],
		rating=request.POST['rating'],
	)
	
	context = {
		'user': user.username,
		'review': request.POST['review'],
		'rating': request.POST['rating'],
		'image': image
	}

	average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))


	return JsonResponse(
		{
			'bool': True,
			'context': context,
			'average_reviews': average_reviews,
		}
	)

def search_view(request):
	# query = request.GET['q'] OR
	query = request.GET.get('q') 

	products = Product.objects.filter(title__icontains=query).order_by('-date')

	context = {
		'products': products,
		'query': query,
	}

	return render(request, 'core/search.html', context)

def filter_product(request):
	categories = request.GET.getlist('category[]')
	vendors = request.GET.getlist('vendor[]')

	min_price = request.GET.get('min_price')
	max_price = request.GET.get('max_price')

	products = Product.objects.filter(product_status='published').order_by('-id').distinct()

	products = products.filter(price__gte=min_price)
	products = products.filter(price__lte=max_price)

	if len(categories) > 0:
		products = products.filter(category__id__in=categories).distinct()
	if len(vendors) > 0:
		products = products.filter(vendor__id__in=vendors).distinct()

	context = {
		'products': products
	}

	data = render_to_string('core/async/product-list.html', context)
	return JsonResponse({'data': data})

def add_to_cart(request):
	cart_product = {}

	cart_product[str(request.GET['id'])] = {
		'qty': request.GET['qty'],
		'title': request.GET['title'],
		'price': request.GET['price'],
		'image': request.GET['image'],
		'pid': request.GET['pid'],
	}

	if 'cart_data_object' in request.session:
		if str(request.GET['id']) in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
			cart_data.update(cart_data)
			request.session['cart_data_object'] = cart_data
		else:
			cart_data = request.session['cart_data_object']
			cart_data.update(cart_product)
			request.session['cart_data_object'] = cart_data
	else:
		request.session['cart_data_object'] = cart_product

	return JsonResponse({
			'data':request.session['cart_data_object'],
			'totalcartitems':len(request.session['cart_data_object'])
		})

def cart_view(request):
	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])

		return render(request, 'core/cart.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
		
	else:
		return render(request, 'core/cart.html')

def delete_from_cart(request):
	product_id = str(request.GET['id'])
	if 'cart_data_object' in request.session:
		if product_id in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			del request.session['cart_data_object'][product_id]
			request.session['cart_data_object'] = cart_data

	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])

	context = render_to_string('core/async/cart-list.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
	return JsonResponse({
			'data': context,
			'totalcartitems': len(request.session['cart_data_object']),
		})

def update_cart(request):
	product_id = str(request.GET['id'])
	product_qty = request.GET['qty']
	if 'cart_data_object' in request.session:
		if product_id in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			cart_data[str(request.GET['id'])]['qty'] = product_qty
			request.session['cart_data_object'] = cart_data

	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])


	context = render_to_string('core/async/cart-list.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
	return JsonResponse({
			'data': context,
			'totalcartitems': len(request.session['cart_data_object']),
		})

@login_required
def wishlist_view(request):
	try:
		wishlist = Wishlist.objects.filter(user=request.user)
	except:
		wishlist = None

	context = {
		'wishlist': wishlist
	}
	return render(request, 'core/wishlist.html', context)

@login_required
def add_to_wishlist(request):
	product_id = request.GET['id']
	product = Product.objects.get(id=product_id)

	context = {}

	wishlist_count = Wishlist.objects.filter(product=product, user=request.user).count()

	if wishlist_count > 0:
		context	= {
			'bool': True,
			'wishlist_count': Wishlist.objects.filter(user=request.user).count()
		}
	else:
		new_wishlist = Wishlist.objects.create(
			product=product,
			user=request.user
		)
		context = {
			'bool': True,
			'wishlist_count': Wishlist.objects.filter(user=request.user).count()
		}

	return JsonResponse(context)

def remove_from_wishlist(request):
	product_id = request.GET['id']
	wishlist = Wishlist.objects.filter(user=request.user)

	product = Wishlist.objects.get(id=product_id)
	product.delete()

	context = {
		'bool': True,
		'wishlist': wishlist
	}
	qs_json = serializers.serialize('json', wishlist)
	data = render_to_string('core/async/wishlist-list.html', context)
	return JsonResponse({'data': data, 'wishlist': qs_json})

def contact(request):
	return render(request, 'core/contact.html')

def ajax_contact_form(request):
	name = request.GET['name']
	email = request.GET['email']
	message = request.GET['message']

	contact = ContactUs.objects.create(
		name=name,		
		email=email,		
		message=message,		
	)

	data = {
		'bool': True,
	}

	return JsonResponse({'data': data})

def about(request):
	return render(request, 'core/about.html')

templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Categories{% endblock title %}

{% block content %}
{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Categories</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Categories</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Category list Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-5">
                <div class="category__list">
                    <!-- <div class="category__list__search">
                        <form action="#">
                            <input type="text" placeholder="Search...">
                            <button type="submit"><span class="icon_search"></span></button>
                        </form>
                    </div> -->
                    <div class="category__list__item">
                        <h4>Categories</h4>
                        {% for c in categories %}
                        <ul>
                            <li><a href="{% url 'core:category-product-list' c.cid %}">{{c.title}} ({{c.category.count}})</a></li>
                        </ul>
                        {% endfor %}
                    </div>
                    <!-- <div class="category__list__item">
                        <h4>Recent News</h4>
                        <div class="category__list__recent">
                            <a href="#" class="category__list__recent__item">
                                <div class="category__list__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-1.jpg" alt="">
                                </div>
                                <div class="category__list__recent__item__text">
                                    <h6>09 Kinds Of Vegetables<br /> Protect The Liver</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                            <a href="#" class="category__list__recent__item">
                                <div class="category__list__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-2.jpg" alt="">
                                </div>
                                <div class="category__list__recent__item__text">
                                    <h6>Tips You To Balance<br /> Nutrition Meal Day</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                            <a href="#" class="category__list__recent__item">
                                <div class="category__list__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-3.jpg" alt="">
                                </div>
                                <div class="category__list__recent__item__text">
                                    <h6>4 Principles Help You Lose <br />Weight With Vegetables</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                        </div>
                    </div> -->
                    <div class="category__list__item">
                        <h4>By Tags</h4>
                        <div class="category__list__item__tags">
                            {% for random_tag in random_product_tags %}
                            <a href="{% url 'core:tags' random_tag.slug %}">#{{ random_tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7">
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                            <div class="filter__sort">
                                <span>Sort By</span>
                                <select>
                                    <option value="0">Default</option>
                                    <option value="0">Default</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                <h6><span>{{ categories.count }}</span> Categorie{{ categories.count|pluralize }} found</h6>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__option">
                                <span class="icon_grid-2x2"></span>
                                <span class="icon_ul"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for c in categories %}
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="category__list__item">
                            <div class="category__list__pic">
                                <a href="{% url 'core:category-product-list' c.cid %}"><img src="{{c.image.url}}" alt=""></a>
                            </div>
                            <div class="category__list__text">
                                <h5><a href="{% url 'core:category-product-list' c.cid %}">{{ c.title }}</a></h5>
                                <p>{{ c.category.count }} Product{{ c.category.count|pluralize }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-lg-12">
                        <div class="product__pagination category__list__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Category list Section End -->


{% endblock content %}

templates/core/category-products-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}{{ category.title }} | Category{% endblock title %}

{% block content %}
{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>{{ category.title }}</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <a href="{% url 'core:category-list' %}">Categories</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>{{ category.title }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Category Products List Section Start -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <!-- <div class="category__list__search">
                    <form action="#">
                        <input type="text" placeholder="Search...">
                        <button type="submit"><span class="icon_search"></span></button>
                    </form>
                </div> -->
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                            <div class="filter__sort">
                                <span>Sort By</span>
                                <select>
                                    <option value="0">Default</option>
                                    <option value="0">Default</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                <h6><span>{{ products.count }}</span>Product{{ products.count|pluralize }} found</h6>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__option">
                                <span class="icon_grid-2x2"></span>
                                <span class="icon_ul"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for p in products %}
                    {% if p.get_percentage > 0 %}
                    <div class="col-lg-3 col-md-4 col-sm-4">
                        <div class="main__product__item">
                            <a href="{% url 'core:products-detail' p.pid %}">
                                <div class="main__product__item__pic set-bg"
                                    data-setbg="{{ p.image.url }}">
                                    <div class="main__product__percent">-{{ p.get_percentage|floatformat:0 }}%</div>
                                    <!-- <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                        <input type="hidden" value="1" class="product-quantity-{{ p.id }}" id="product-quantity">
                                        <input type="hidden" value="{{ p.pid }}" class="product-pid-{{ p.id }}">
                                        <input type="hidden" value="{{ p.image.url }}" class="product-image-{{ p.id }}">
                                        <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">
                                        <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">
                                        <li><button data-index='{{ p.id }}' class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i></button></li>
                                    </ul> -->
                                </div>
                            </a>
                            <div class="main__product__item__text">
                                <span>{{ p.category.title }}</span>
                                <h5><a href="{% url 'core:products-detail' p.pid %}">{{ p.title }}</a></h5>
                                <span style="display: none" class="current-product-price-{{ p.id }}">{{ p.price }}</span>
                                <div class="product__item__price">${{ p.price }} <span>${{ p.old_price }}</span></div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="col-lg-3 col-md-4 col-sm-4">
                        <div class="main__product__item">
                            <a href="{% url 'core:products-detail' p.pid %}">
                                <div class="main__product__item__pic set-bg"
                                    data-setbg="{{ p.image.url }}">
                                    <!-- <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                        <input type="hidden" value="1" class="product-quantity-{{ p.id }}" id="product-quantity">
                                        <input type="hidden" value="{{ p.pid }}" class="product-pid-{{ p.id }}">
                                        <input type="hidden" value="{{ p.image.url }}" class="product-image-{{ p.id }}">
                                        <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">
                                        <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">
                                        <li><button data-index='{{ p.id }}' class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i></button></li>
                                    </ul> -->
                                </div>
                            </a>
                            <div class="main__product__item__text">
                                <span>{{ p.category.title }}</span>
                                <h5><a href="{% url 'core:products-detail' p.pid %}">{{ p.title }}</a></h5>
                                <span style="display: none" class="current-product-price-{{ p.id }}">{{ p.price }}</span>
                                <div class="product__item__price">${{ p.price }}</div>
                            </div>
                        </div>
                    </div> 
                    {% endif %}
                    {% endfor %}   
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Category Products List Section End -->

{% endblock content %}

templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Vendors{% endblock title %}

{% block content %}
{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Vendors</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Vendors</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Vendor Section Start -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <!-- <div class="category__list__search">
                    <form action="#">
                        <input type="text" placeholder="Search...">
                        <button type="submit"><span class="icon_search"></span></button>
                    </form>
                </div> -->
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                            <div class="filter__sort">
                                <span>Sort By</span>
                                <select>
                                    <option value="0">Default</option>
                                    <option value="0">Default</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                <h6><span>{{vendors.count}}</span>Vendor{{vendors.count|pluralize}} found</h6>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__option">
                                <span class="icon_grid-2x2"></span>
                                <span class="icon_ul"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">

                    {% for v in vendors %}

                    <div class="col-lg-3 col-md-12 col-sm-12">
                        <div class="vendor__item">
                            <a href="{% url 'core:vendor-detail' v.vid %}">
                                <div class="vendor__item__pic set-bg" data-setbg="{{v.image.url}}"></div>
                            </a>
                            <div class="vendor__item__text">
                                <span>Since {{v.date|date:'Y'}}</span>
                                <h5><a href="{% url 'core:vendor-detail' v.vid %}"><strong>{{v.title}}</strong></a></h5>
                                <span>Our address: {{v.address}}</span>
                                <span>Call us: {{v.contact}}</span>
                            </div>
                        </div>
                    </div> 

                    {% endfor %}  
                      
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Vendor Section End -->




{% endblock content %}