blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

	# Blogpage
	path('', views.blog_view, name='blog'),

	# Post Details
	path('post/<pid>/', views.blog_detail_view, name='blog-detail'),

	# Blog Category
	path('category/<cid>/', views.blog_category_view, name="blog-category"),

	# Blog Tags
	path('tag/<slug:tag_slug>/', views.blog_tags, name='blog-tag'),

	# Add Post Comment
	path('ajax-add-comment/<int:pid>/', views.ajax_add_comment, name='ajax-add-comment'),

]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [

	# Homepage
	path('', views.index, name='index'),
	
	# Product
	path('products/', views.products_list_view, name='products-list'),
	path('product/<pid>/', views.product_detail_view, name='products-detail'),

	# Category
	path('category/', views.category_list_view, name='category-list'),
	path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

	# Vendor
	path('vendors/', views.vendor_list_view, name='vendor-list'),
	path('vendor/<vid>/', views.vendor_detail_view, name='vendor-detail'),

	# Tags
	path('products/tag/<slug:tag_slug>/', views.tags_list, name='tags'),

	# Add Product Review
	path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax-add-review'),

	# Seacrh 
	path('search/', views.search_view, name='search'),

	# Product Filter
	path('filter-product/', views.filter_product, name='filter-product'),

	# Add To Cart 
	path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

	# Cart Page
	path('cart/', views.cart_view, name='cart'),

	# Delete from cart
	path('delete-from-cart/', views.delete_from_cart, name='delete-from-cart'),

	# Update cart
	path('update-cart/', views.update_cart, name='update-cart'),

	# Wishlist page
	path('wishlist/', views.wishlist_view, name='wishlist'),

	# Add To Wishlist
	path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),

	# Remove From Wishlist
	path('remove-from-wishlist/', views.remove_from_wishlist, name='remove-from-wishlist'),

	# Contact
	path('contact/', views.contact, name='contact'),

	# Ajax Contact From
	path('ajax-contact-form/', views.ajax_contact_form, name='ajax-contact-form'),

	# About Us
	path('about/', views.about, name='about'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


### TEST ###

# handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'

blog/models.py
from django.db import models
from django.utils.html import mark_safe
from userauths.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from shortuuid.django_fields import ShortUUIDField

STATUS = (
	("draft", "Draft"),
	("disabled", "Disabled"),
	("rejected", "Rejected"),
	("in_review", "In Review"),
	("published", "Published"),
)

class Category(models.Model):
	cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix='cat', alphabet='abcdefgh12345')
	title = models.CharField(max_length=100, default="Category Name")

	class Meta:
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.title

class Post(models.Model):
	pid = ShortUUIDField(unique=True, length=10, max_length=30, alphabet='abcdefgh12345')

	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	categories = models.ManyToManyField(Category, related_name="categories")

	tags = TaggableManager(blank=True)

	image = models.ImageField(upload_to='blog', default="blog.jpg")
	title = models.CharField(max_length=100, default="Post Name")
	subtitle = models.TextField(null=True, blank=True, default="Post Subtitle")
	
	body = RichTextUploadingField(null=True, blank=True, default="Post Body")

	post_status = models.CharField(choices=STATUS, max_length=10, default="in_review")
	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = 'Posts'

	def blog_image(self):
		return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))

	def __str__(self):
		return self.title

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	body = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Comments'

	def __str__(self):
		return self.post.title

blog/forms.py
from django import forms
from blog.models import Comment

class CommentFrom(forms.ModelForm):
	comment = forms.CharField(widget=forms.Textarea(attrs={
		'placeholder': 'Write comment', 
		'class': "form-control", 
		'id': "textAreaExample", 
		'rows': "4", 
		'style': "background: #fff;"}))

	class Meta:
		model = Comment
		fields = ['comment']

blog/views.py
from django.shortcuts import render
from django.http import JsonResponse
from blog.models import Post, Comment, Category
from blog.forms import CommentFrom
from taggit.models import Tag

def blog_view(request):
	posts = Post.objects.filter(post_status='published').order_by("-date_created")

	context = {
		"posts": posts,
	}
	return render(request, 'blog/blog.html', context)

def blog_category_view(request, cid):
	category = Category.objects.get(cid=cid)
	posts = Post.objects.filter(
		post_status='published', categories=category
	).order_by("-date_created")

	context = {
		"category": category,
		"posts": posts,
	}
	return render(request, "blog/category.html", context)

def blog_detail_view(request, pid):
	post = Post.objects.get(pid=pid)
	posts = Post.objects.filter(categories__in=post.categories.all()).exclude(pid=pid).distinct()
	comments = Comment.objects.filter(post=post).order_by('-date_created')

	comment_form = CommentFrom()

	make_comment = True
	if request.user.is_authenticated:
		user_comment_count = Comment.objects.filter(
			user=request.user, 
			post=post
		).count() 

		if user_comment_count > 0:
			make_comment = False

	context = {
		"post": post,
		"comments": comments,
		"comment_form": comment_form,
		"make_comment": make_comment,
		"posts": posts,
	}
	return render(request, 'blog/blog-detail.html', context)

def blog_tags(request, tag_slug=None):
	posts = Post.objects.filter(post_status='published').order_by('-id')

	tag = None
	if tag_slug:
		tag = Tag.objects.get(slug=tag_slug)
		posts = posts.filter(tags__in=[tag])

	context = {
		'posts': posts,
		'tag': tag,
	}
	return render(request, 'blog/tag.html', context)

def ajax_add_comment(request, pid):
	post = Post.objects.get(pk=pid)
	user = request.user
	image = user.image.url

	comment = Comment.objects.create(
		user=user,
		post=post,
		body=request.POST['comment'],
	)
	
	context = {
		'user': user.username,
		'comment': request.POST['comment'],
		'image': image
	}
	return JsonResponse(
		{
			'bool': True,
			'context': context,
		}
	)

templates/blog/blog-detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

{% include 'partials/hero-section.html' %}

<!-- Blog Details Hero Begin -->
<section class="blog-details-hero set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog__details__hero__text">
                    <h2>{{ post.title }}</h2>
                    <ul>
                        <li>By {{ post.user.name }}</li>
                        <li>{{ post.date_created|date:"d M, Y" }}</li>
                        <li>{{ comments.count }} Comment{{ comments.count|pluralize }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Hero End -->

<!-- Blog Details Section Begin -->
<section class="blog-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-5 order-md-1 order-2 mt-5">
                <div class="blog__sidebar">
                    <div class="blog__sidebar__search">
                        <form action="#">
                            <input type="text" placeholder="Search...">
                            <button type="submit"><span class="icon_search"></span></button>
                        </form>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Categories</h4>
                        {% for c in blog_categories %}
                        <ul>
                            <li><a href="{% url 'blog:blog-category' c.cid %}">{{ c.title }} ({{c.categories.count}})</a></li>
                        </ul>
                        {% endfor %}
                    </div>
                    <!-- <div class="blog__sidebar__item">
                        <h4>Recent News</h4>
                        <div class="blog__sidebar__recent">
                            <a href="#" class="blog__sidebar__recent__item">
                                <div class="blog__sidebar__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-1.jpg" alt="">
                                </div>
                                <div class="blog__sidebar__recent__item__text">
                                    <h6>09 Kinds Of Vegetables<br /> Protect The Liver</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                            <a href="#" class="blog__sidebar__recent__item">
                                <div class="blog__sidebar__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-2.jpg" alt="">
                                </div>
                                <div class="blog__sidebar__recent__item__text">
                                    <h6>Tips You To Balance<br /> Nutrition Meal Day</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                            <a href="#" class="blog__sidebar__recent__item">
                                <div class="blog__sidebar__recent__item__pic">
                                    <img src="img/blog/sidebar/sr-3.jpg" alt="">
                                </div>
                                <div class="blog__sidebar__recent__item__text">
                                    <h6>4 Principles Help You Lose <br />Weight With Vegetables</h6>
                                    <span>MAR 05, 2019</span>
                                </div>
                            </a>
                        </div>
                    </div> -->
                    <div class="blog__sidebar__item">
                        <h4>By Tags</h4>
                        <div class="blog__sidebar__item__tags">
                            {% for random_tag in random_blog_tags %}
                            <a href="{% url 'blog:blog-tag' random_tag.slug %}">#{{ random_tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7 order-md-1 order-1">
                <div class="blog__details__text">
                    <img src="{{ post.image.url }}" alt="">
                    <p>{{ post.subtitle }}</p>
                    <p>{{ post.body|safe }}</p>
                </div>
                <div class="blog__details__content">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="blog__details__author">
                                <div class="blog__details__author__pic">
                                    <img src="{{ post.user.image.url }}" alt="">
                                </div>
                                <div class="blog__details__author__text">
                                    <h6>{{ post.user.name }}</h6>
                                    <span>{{ post.user.username }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="blog__details__widget">
                                <ul>
                                    <li class="blog__category"><span>Categories:</span> {% for category in post.categories.all %}• <a href="{% url 'blog:blog-category' category.cid %}">{{ category.title }}</a> {% endfor %}</li>
                                    <li><span>Tags:</span> {% for tag in post.tags.all %}<a href="{% url 'blog:blog-tag' tag.slug %}" class="tag">#{{tag.name}}</a> {% endfor %}</li>        
                                </ul>
                                <div class="blog__details__social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-google-plus"></i></a>
                                    <a href="#"><i class="fa fa-linkedin"></i></a>
                                    <a href="#"><i class="fa fa-envelope"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 mt-5">
                            <h4 style="color: #1c1c1c;" class="text-center font-weight-bold mb-3">Comments</h4>
                          <div class="card">
                            {% for c in comments %}
                            <div class="card-body">
                                
                              <div class="d-flex flex-start align-items-center">
                                <img class="rounded-circle shadow-1-strong mr-3" src="{{c.user.image.url}}" alt="avatar" width="60" height="60" />
                                <div>
                                  <h6 class="font-weight-bold mb-1">{{c.user.username}}</h6>
                                  <p class="text-muted small mb-0">
                                    {{c.date_created|date:"d M, Y"}}
                                  </p>
                                </div>
                              </div>
                                
                              <p class="mt-3">
                                {{c.body}}
                              </p>

                            </div>
                            <hr class="my-0">
                            {% endfor %}
                            {% if request.user.is_authenticated %}
                            {% if make_comment == True %}
                            <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
                                <strong id="blogCommentRes"></strong>
                                <form class="hide-comment" action="{% url 'blog:ajax-add-comment' post.id %}" id="blogCommentForm" method="POST">
                                {% csrf_token %}
                                  <div class="d-flex flex-start w-100">
                                    
                                    <div class="form-outline w-100">
                                      <!-- <textarea class="form-control" id="textAreaExample" rows="4" style="background: #fff;"></textarea> -->
                                      {{comment_form.comment}}
                                      <label class="form-label" for="textAreaExample">Message</label>
                                    </div>
                                  </div>
                                  <div class="float-right">
                                    <button type="submit" class="btn btn-primary btn-sm">Post comment</button>
                                    <!-- <button type="button" class="btn btn-outline-primary btn-sm">Cancel</button> -->
                                  </div>
                                </form>
                            </div>
                            {% endif %}
                            {% else %}
                            <strong class="text-center">To leave comments, you should be authenticated! Please create or log into your account.</strong>
                            {% endif %}
                          </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Section End -->

<!-- Related Blog Section Begin -->
<section class="related-blog spad">
    <div class="container">
        <div class="row">
            {% if posts %}
            <div class="col-lg-12">
                <div class="section-title related-blog-title">
                    <h2>Post You May Like</h2>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="row">
            {% for p in posts %}
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <a href="{% url 'blog:blog-detail' p.pid %}"><img src="{{ p.image.url }}" alt=""></a>
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> {{ p.date_created|date:"d M, Y" }}</li>
                            <li><i class="fa fa-comment-o"></i> {{ p.comments.count }}</li>
                        </ul>
                        <h5><a href="{% url 'blog:blog-detail' p.pid %}">{{ p.title }}</a></h5>
                        <p>{{ p.subtitle|truncatechars:150 }} </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</section>
<!-- Related Blog Section End -->
<!-- <script src="{% static './assets/js/bootstrap5.min.js' %}"></script> -->
{% endblock content %}

templates/blog/blog.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Blog{% endblock title %}

{% block content %}

{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Blog</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Blog</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Blog Section Begin -->
<section class="blog spad">
    <div class="container">
        <div class="row">
            {% include 'partials/blog-sidebar.html' %}
            <div class="col-lg-8 col-md-7">
                <div class="row">
                	{% for p in posts %}
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic">
                                <a href="{% url 'blog:blog-detail' p.pid %}"><img src="{{ p.image.url }}" alt=""></a>
                            </div>
                            <div class="blog__item__text">
                                <ul>
                                    <li><i class="fa fa-calendar-o"></i> {{ p.date_created|date:"d M, Y" }}</li>
                                    <li><i class="fa fa-comment-o"></i> {{ p.comments.count }}</li>
                                </ul>
                                <h5><a href="{% url 'blog:blog-detail' p.pid %}">{{ p.title }}</a></h5>
                                <p>{{ p.subtitle|truncatechars:150 }}</p>
                                <a href="{% url 'blog:blog-detail' p.pid %}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-lg-12">
                        <div class="product__pagination blog__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->


{% endblock content %}

templates/blog/category.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}{{category.title}}{% endblock title %}

{% block content %}

{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>{{category.title}}</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <a href="{% url 'blog:blog' %}">Blog</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Category</span>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>{{category.title}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Blog Section Begin -->
<section class="blog spad">
    <div class="container">
        <div class="row">
            {% include 'partials/blog-sidebar.html' %}
            <div class="col-lg-8 col-md-7">
                <div class="row">
                	{% for p in posts %}
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic">
                                <a href="{% url 'blog:blog-detail' p.pid %}"><img src="{{ p.image.url }}" alt=""></a>
                            </div>
                            <div class="blog__item__text">
                                <ul>
                                    <li><i class="fa fa-calendar-o"></i> {{ p.date_created|date:"d M, Y" }}</li>
                                    <li><i class="fa fa-comment-o"></i> {{ p.comments.count }}</li>
                                </ul>
                                <h5><a href="{% url 'blog:blog-detail' p.pid %}">{{ p.title }}</a></h5>
                                <p>{{ p.subtitle|truncatechars:150 }}</p>
                                <a href="{% url 'blog:blog-detail' p.pid %}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-lg-12">
                        <div class="product__pagination blog__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->


{% endblock content %}

templates/blog/tag.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Tag{% endblock title %}

{% block content %}

{% include 'partials/hero-section.html' %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>#{{tag.name}}</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <a href="{% url 'blog:blog' %}">Blog</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Tag</span>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>#{{tag.name}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Blog Section Begin -->
<section class="blog spad">
    <div class="container">
        <div class="row">
            {% include 'partials/blog-sidebar.html' %}
            <div class="col-lg-8 col-md-7">
                <div class="row">
                	{% for p in posts %}
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic">
                                <a href="{% url 'blog:blog-detail' p.pid %}"><img src="{{ p.image.url }}" alt=""></a>
                            </div>
                            <div class="blog__item__text">
                                <ul>
                                    <li><i class="fa fa-calendar-o"></i> {{ p.date_created|date:"d M, Y" }}</li>
                                    <li><i class="fa fa-comment-o"></i> {{ p.comments.count }}</li>
                                </ul>
                                <h5><a href="{% url 'blog:blog-detail' p.pid %}">{{ p.title }}</a></h5>
                                <p>{{ p.subtitle|truncatechars:150 }}</p>
                                <a href="{% url 'blog:blog-detail' p.pid %}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-lg-12">
                        <div class="product__pagination blog__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->


{% endblock content %}